### ISSUE TITLE
Can't login in "https://wwdev.vercel.app/"

### ISSUE THREAD

**Issue by andresousadotpt** [EddyPBR/world-wide-dev#1]
When logging in with github this error occurs!
![image](https://user-images.githubusercontent.com/62852511/157292275-ce6c27cf-1700-4bc5-82a0-0807c3263388.png)

**Comment by EddyPBR** [comment]
Hello, we were working with the production database these days. If possible please try again, any problems please let us know again.

We really appreciate the feedback! 
thank you!
